default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: nomster_development
  username: landocondra


test:
  <<: *default
  database: nomster_test
  username: landocondra

production:
  <<: *default
  database: nomster_production
  # username: nomster
  # password: <%= ENV['NOMSTER_DATABASE_PASSWORD'] %>
 
 
 
 
 